project:
  pre-render:
    - R/00-adam.R
    - R/01-tlf-numbers.R
  execute-dir: project

profile:
  group:
    - [book, doc]

bibliography: references.bib

knitr:
  opts_chunk:
    dev: svglite
    fig.showtext: false
